name = "blog"
node_compat = true
compatibility_date = "2023-07-24"

main = "src/index.ts"

[env.dev]
workers_dev = true
kv_namespaces = [
  { binding = "CACHED_RESPONSE", id = "d50e6b7d42cb4529a69795fcdea547e7", preview_id = "6282b0fbc13a4ec796c4b0c82dcb5ecd" }
]

[env.production]
route = { pattern = "*waka.dev/*", zone_name = "waka.dev" }
kv_namespaces = [
  { binding = "CACHED_RESPONSE", id = "a73df32e3f3f4711b4e8fd7c310764d9" }
]
